"""
Training data for expense categorization model.
This provides initial training data for the NLP categorization model.
"""

# Training data: (description, category)
TRAINING_DATA = [
    # Food & Dining
    ("McDonald's breakfast", "Food"),
    ("Starbucks coffee", "Food"),
    ("Pizza Hut delivery", "Food"),
    ("Subway sandwich", "Food"),
    ("Domino's pizza", "Food"),
    ("KFC dinner", "Food"),
    ("Burger King lunch", "Food"),
    ("Restaurant dinner", "Food"),
    ("Grocery store", "Food"),
    ("Supermarket shopping", "Food"),
    ("Food delivery Uber Eats", "Food"),
    ("Swiggy order", "Food"),
    ("Zomato food", "Food"),
    ("Cafe coffee", "Food"),
    ("Bakery items", "Food"),
    ("Ice cream shop", "Food"),
    ("Taco Bell", "Food"),
    ("Chipotle burrito", "Food"),
    ("Panera Bread", "Food"),
    ("Dunkin Donuts", "Food"),
    
    # Transport
    ("Uber ride", "Transport"),
    ("Lyft to airport", "Transport"),
    ("Taxi fare", "Transport"),
    ("Gas station fuel", "Transport"),
    ("Petrol pump", "Transport"),
    ("Car maintenance", "Transport"),
    ("Oil change service", "Transport"),
    ("Metro card", "Transport"),
    ("Bus ticket", "Transport"),
    ("Train ticket", "Transport"),
    ("Flight booking", "Transport"),
    ("Parking fee", "Transport"),
    ("Toll charges", "Transport"),
    ("Car insurance", "Transport"),
    ("Vehicle registration", "Transport"),
    ("Ola cab", "Transport"),
    ("Auto rickshaw", "Transport"),
    ("Bike rental", "Transport"),
    ("Car wash", "Transport"),
    ("Tire replacement", "Transport"),
    
    # Entertainment
    ("Netflix subscription", "Entertainment"),
    ("Spotify premium", "Entertainment"),
    ("Amazon Prime", "Entertainment"),
    ("Disney Plus", "Entertainment"),
    ("Movie tickets", "Entertainment"),
    ("Concert tickets", "Entertainment"),
    ("Gaming subscription", "Entertainment"),
    ("PlayStation game", "Entertainment"),
    ("Xbox game pass", "Entertainment"),
    ("Steam game purchase", "Entertainment"),
    ("Theatre show", "Entertainment"),
    ("Amusement park", "Entertainment"),
    ("Zoo tickets", "Entertainment"),
    ("Museum entry", "Entertainment"),
    ("Sports event", "Entertainment"),
    ("Music festival", "Entertainment"),
    ("YouTube Premium", "Entertainment"),
    ("Audible subscription", "Entertainment"),
    ("Kindle books", "Entertainment"),
    ("Cable TV", "Entertainment"),
    
    # Shopping
    ("Amazon purchase", "Shopping"),
    ("Walmart shopping", "Shopping"),
    ("Target store", "Shopping"),
    ("Clothing store", "Shopping"),
    ("Shoe purchase", "Shopping"),
    ("Electronics store", "Shopping"),
    ("Best Buy gadget", "Shopping"),
    ("Furniture store", "Shopping"),
    ("IKEA shopping", "Shopping"),
    ("Home Depot supplies", "Shopping"),
    ("Pharmacy items", "Shopping"),
    ("Cosmetics store", "Shopping"),
    ("Jewelry purchase", "Shopping"),
    ("Book store", "Shopping"),
    ("Gift purchase", "Shopping"),
    ("Sports equipment", "Shopping"),
    ("Pet supplies", "Shopping"),
    ("Garden supplies", "Shopping"),
    ("Online shopping", "Shopping"),
    ("Department store", "Shopping"),
    
    # Bills & Utilities
    ("Electricity bill", "Bills"),
    ("Water bill", "Bills"),
    ("Internet bill", "Bills"),
    ("Phone bill", "Bills"),
    ("Gas bill", "Bills"),
    ("Cable bill", "Bills"),
    ("HOA fees", "Bills"),
    ("Rent payment", "Bills"),
    ("Mortgage payment", "Bills"),
    ("Property tax", "Bills"),
    ("Insurance premium", "Bills"),
    ("Credit card payment", "Bills"),
    ("Loan payment", "Bills"),
    ("Mobile recharge", "Bills"),
    ("DTH recharge", "Bills"),
    ("Broadband bill", "Bills"),
    ("Sewage charges", "Bills"),
    ("Maintenance charges", "Bills"),
    ("Society charges", "Bills"),
    ("Subscription renewal", "Bills"),
    
    # Healthcare
    ("Doctor visit", "Healthcare"),
    ("Hospital bill", "Healthcare"),
    ("Pharmacy medicine", "Healthcare"),
    ("Dental checkup", "Healthcare"),
    ("Eye exam", "Healthcare"),
    ("Lab tests", "Healthcare"),
    ("X-ray scan", "Healthcare"),
    ("Physiotherapy", "Healthcare"),
    ("Health insurance", "Healthcare"),
    ("Vaccination", "Healthcare"),
    ("Medical supplies", "Healthcare"),
    ("Prescription refill", "Healthcare"),
    ("Emergency room", "Healthcare"),
    ("Surgery cost", "Healthcare"),
    ("Therapy session", "Healthcare"),
    ("Clinic visit", "Healthcare"),
    ("Medical equipment", "Healthcare"),
    ("Health checkup", "Healthcare"),
    ("Vitamins supplements", "Healthcare"),
    ("Gym membership", "Healthcare"),
    
    # Education
    ("Course fee", "Education"),
    ("Tuition payment", "Education"),
    ("Books purchase", "Education"),
    ("School supplies", "Education"),
    ("Online course", "Education"),
    ("Udemy course", "Education"),
    ("Coursera subscription", "Education"),
    ("Workshop registration", "Education"),
    ("Conference fee", "Education"),
    ("Certification exam", "Education"),
    ("Study materials", "Education"),
    ("Training program", "Education"),
    ("Educational software", "Education"),
    ("Library fine", "Education"),
    ("Student loan", "Education"),
    ("Private tutoring", "Education"),
    ("Language classes", "Education"),
    ("Music lessons", "Education"),
    ("Art classes", "Education"),
    ("Coaching center", "Education"),
    
    # Personal Care
    ("Haircut salon", "Personal Care"),
    ("Spa treatment", "Personal Care"),
    ("Massage therapy", "Personal Care"),
    ("Beauty salon", "Personal Care"),
    ("Gym membership", "Personal Care"),
    ("Yoga classes", "Personal Care"),
    ("Personal trainer", "Personal Care"),
    ("Skincare products", "Personal Care"),
    ("Haircare products", "Personal Care"),
    ("Grooming supplies", "Personal Care"),
    ("Nail salon", "Personal Care"),
    ("Barber shop", "Personal Care"),
    ("Fitness equipment", "Personal Care"),
    ("Wellness center", "Personal Care"),
    ("Meditation app", "Personal Care"),
    
    # Travel
    ("Hotel booking", "Travel"),
    ("Airbnb stay", "Travel"),
    ("Flight ticket", "Travel"),
    ("Travel insurance", "Travel"),
    ("Luggage purchase", "Travel"),
    ("Travel agency", "Travel"),
    ("Tour package", "Travel"),
    ("Visa fees", "Travel"),
    ("Passport renewal", "Travel"),
    ("Foreign exchange", "Travel"),
    ("Travel essentials", "Travel"),
    ("Resort booking", "Travel"),
    ("Cruise booking", "Travel"),
    ("Car rental vacation", "Travel"),
    ("Travel guide book", "Travel"),
    
    # Miscellaneous
    ("ATM withdrawal", "Other"),
    ("Bank charges", "Other"),
    ("Donation", "Other"),
    ("Charity", "Other"),
    ("Gift given", "Other"),
    ("Laundry service", "Other"),
    ("Dry cleaning", "Other"),
    ("Post office", "Other"),
    ("Printing services", "Other"),
    ("Legal fees", "Other"),
    ("Accounting fees", "Other"),
    ("Professional services", "Other"),
    ("Membership fee", "Other"),
    ("Subscription box", "Other"),
    ("Pet care", "Other"),
]

# Category list
CATEGORIES = [
    "Food",
    "Transport",
    "Entertainment",
    "Shopping",
    "Bills",
    "Healthcare",
    "Education",
    "Personal Care",
    "Travel",
    "Other"
]